[package]
name = "iibhf-devteam/iibhf-tester"
description = "A simple testing library for roblox games."
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/IIBHF-DevTeam/iibhf-tester/tree/main"
license = "MIT"


[dependencies]
promise = "evaera/promise@4.0.0"
